<a href="https://colab.research.google.com/github/magotheinnocent/MachineLearningTasksGroup5/blob/master/cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pyplot
import seaborn as sb

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split


Importing dependencies

In [ ]:
calif = fetch_california_housing()



Importing the dataset

In [ ]:
kf= KFold(n_splits = 4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [ ]:
for train_index, test_index in kf.split(calif):
    print (train_index, test_index)

[1 2 3] [0]
[0 2 3] [1]
[0 1 3] [2]
[0 1 2] [3]


A higher value of K means less accuraccy in the testing set depending on data size. For instance, using a K of 10 in data with only 10 records means only 1 will be used for testing, hence not a good determinant of accuraccy but if there are 10,000 records and 1000 are used for testing, it might be an accurate determinant. The default recommended value of K is 5 to give 20% of the reecords for testing the model's accuracy

In [ ]:
## 4 split